### ISSUE TITLE
'shape' deprecation issue.

### ISSUE THREAD

**Issue by bormanst** [jayeshmahapatra/triton-fastapi-docker#1]
gradio/app.py line 60:

-- inputs=gr.Image(shape=(224, 224)),
++ inputs=gr.Image(width=224, height=224),

Thanks for your work, it is appreciated.

**Comment by jayeshmahapatra** [comment]
Thanks for the comment.

Instead of upgrading the code to match the latest versions of dependencies, I added the exact version numbers in requirements.txt which are compatible with the code. This should allow reproducibility without constant code changes on my end.
